### PR TITLE
Issue 72 and 73

### PR DESCRIPTION
**Pull request by kushankr**
Created User Profile Page.
User can change his/her username and password.

### CODE REVIEW

**Comment by rupalkhilari** [comment]
Thanks a ton, Kushank ! I shall check it out and let you know within a day or two.

**Comment by kushankr** [comment]
Thank you Rupal! I look forward to your feedback !

**Comment by kushankr** [comment]
Hi Rupal,

Thank you for your feedback.  I will work on the comments.

Regarding moving code to approval_frame, there is no views.py in approval_frame folder. I need to create one. I hope that is ok?

**Comment by kushankr** [comment]
Also,
I am new to git. To update my pull request, should i just update my code and commit to my repository and my pull request will be updated?

**Comment by rupalkhilari** [comment]
Hi Kushank, 

Yes, creating a new approval_frame/views.py should be alright if that works. Regarding git, it is ideal if you create a different feature in its own branch in your own repository (separate from master) and then submit a pull request. But yes, as you mentioned, for now you should be able to update the pull request by simply committing to the same master branch in your forked repository. The pull request in electology will be automatically be updated. 
Hope this helps.
Thanks!

**Comment by kushankr** [comment]
Thank you, Rupal.

I will work on your comments. Thank you for taking time out to review my changes.

**Comment by kushankr** [comment]
.

**Comment by kushankr** [comment]
Hi Rupal

Thank you so much for your feedback. It was very helpful. I worked on it and have updated the pull request. Please review it. Also, I have tested the code and it is all good but if you can please check the code working, that will be great. 

Your comments helped immensely. It helped me identify another bug (in addition to the one you identified) in the 'Member since' and 'Last Login' tests. I was able to fix the tests. And second, there is a lot more consistency in the code. Your comments about moving 'username change' and 'password change' code and tests to approval_frame folder has made the code a lot better.

I have one question about one of the comments: 
"I think you missed this Thumbs.db file that was committed into the repo. You could perhaps git-rm it and add it into the .gitignore file." 
-> is this file not supposed to be committed? should i remove it from the commit? and when you say 'add it into the .gitignore' file  -> right now there is no such path as 'approval_frame/approval_polls/static/approval_polls/images/Thumbs.db' in the .gitignore file. I was wondering about how did i manage to get this file committed, i did not change anything related to this. 

Thank you so much for your help, Rupal.

**Comment by kushankr** [comment]
I have removed Thumbs.db file.  It is no longer a part of the commit.

Can you please review my pull request, Rupal and please let me know if there is anything else i need to do.

**Comment by rupalkhilari** [comment]
Thanks so much Kushank ! I shall review your changes as soon as I can and merge them with the master branch.

**Comment by kushankr** [comment]
Thank you, Rupal. 
One question and I am sorry if i am bothering you with this: I removed 'Thumbs.db' from the directory it was contained in. So it no longer exists and is no longer a part of my commit/ pull request. If I add 'Thumbs.db' to .gitignore, it won't show an error right since the file no longer exists or is committed? Also, can i add 'Thumbs.db' to my repo .gitignore and update this pull request (instead of editing the main file) ?

**Comment by kushankr** [comment]
Rupal, I have made the change to '.gitignore' as a part of this pull request. But please look at my comment above too.

**Comment by rupalkhilari** [comment]
Yes, Kushank. I actually meant the same - that you could add the line in the .gitignore of the repository and push a new commit. I think I misunderstood what you meant when you mentioned 'new .gitignore file' . So all looks good now :smiley: 
Also, if the file (Thumbs.db) does not exist in the repository but is present in the .gitignore, it will simply ignore it without erroring out. But in case it might be generated again in the future (as it is a temporary thumbnail cache for the windows folder) ,it will continue to ignore it for future commits as well. 
Thanks!

**Comment by kushankr** [comment]
Got it, Rupal ! Thank you.

**Comment by kushankr** [comment]
Thank you, Rupal!! This was a critical bug and I missed it ! Thank you so much.

I have fixed it, also added a test for it. I have updated the pull request. I have tested the code again and it is working fine. If you can also please check it once, that will be great. 

Once again, thank you for reviewing my changes. It has been very helpful.

**Comment by rupalkhilari** [comment]
Thanks for fixing it so promptly !

**Comment by rupalkhilari** [comment]
Hi @kushankr , as you must have noticed, I needed to make a few minor plain formatting changes to your commit as a part of https://github.com/electology/approval_frame/pull/85 so that all the code throughout the project passes the flake8 style check (as updated in the README.md). Sorry I missed out on informing you yesterday !

**Comment by kushankr** [comment]
Hi Rupal,

Thank you for applying formatting changes to my commits.

**Pull request merged**
