### PR TITLE
Issue 69 - Integrating Social Authentication

### PR DESCRIPTION
**Pull request by kushankr**
Integrated Google and Facebook Login.

### CODE REVIEW

**Comment by kushankr** [comment]
@rupalkhilari 

I wanted to share a couple of notes regarding this PR:

1. You need to run 'manage.py syncdb' as the new code in 'settings.py' has to create new database tables. I tried to see if it makes new migrations in migrations folder and there were none (as no models were modified i guess). 

2. Once it is done, please go through the steps in 'Social_Auth_Configure.md' to generate your API keys for Facebook login and Google login. I have my keys in 'local_settings.py' and I can share it with you if you would prefer that. These keys are only for development and testing purposes. If and when we move this change to test server, I need to generate separate keys for our test server URL. 

Can you please review this PR, Rupal? Please test out the changes and let me know what you think. 

Thanks, Rupal.

**Comment by kushankr** [comment]
I am working on this to fix one issue that I noticed, Rupal. I will update the PR.

**Comment by kushankr** [comment]
I have fixed the issue I noticed, Rupal. I look forward to receiving your feedback. Thanks a lot, Rupal.

**Comment by rupalkhilari** [comment]
Thanks, Kushank for your updates! I shall check it out as soon as possible as get back.

**Comment by kushankr** [comment]
@rupalkhilari 

Thank you so much, Rupal for your feedback. Thank you SO MUCH for linking to valuable resources and suggesting bug fixes. 

I have updated the PR as per your comments. Please review the updated PR. Thank you for your review, Rupal.

**Pull request merged**
