### PR TITLE
Resolved Issue 65, 49 and 78

### PR DESCRIPTION
**Pull request by kushankr**
1. A user can delete a poll by clicking 'remove' button in 'My Polls'
page.
2. If a poll administrator has allowed a write-in option for a poll, a
participant can add an additional option by typing it in and select that
option if they choose.
3. Allow a poll to be configured to display the option with the leading
number of votes in a different color.

### CODE REVIEW

**Comment by kushankr** [comment]
@rupalkhilari 

Please review my PR and let me know what you think. Thank you, Rupal.

**Comment by rupalkhilari** [comment]
Thanks Kushank, since I am a bit caught up with some work today, I shall review this and get back to you by tomorrow. Sorry !

**Comment by kushankr** [comment]
Please take your time, Rupal!

**Comment by kushankr** [comment]
Thank you, Rupal for your feedback. I will work on your comments.

**Comment by kushankr** [comment]
Updated the PR, Rupal. Please review it and let me know if i missed anything. Thanks, Rupal.

**Comment by kushankr** [comment]
@rupalkhilari

Updated the PR, Rupal. Can you please review it and let me know if i missed anything. Thanks, Rupal.

**Comment by rupalkhilari** [comment]
Thanks Kushank, for promptly addressing the review comments. There were a couple of minor points that I wanted to check with you about, which I have commented inline.

**Comment by kushankr** [comment]
@rupalkhilari 

Thank you, Rupal, for reviewing the PR and sharing your comments.

I have updated the PR as per your comments.

Thank you, Rupal, for taking the time out to review my changes.

**Comment by rupalkhilari** [comment]
Thank you, Kushank for your valuable contributions!

**Comment by kushankr** [comment]
Thank you, Rupal!

**Pull request merged**
