### PR TITLE
Issue81: Create optional countdown for when a poll closes

### PR DESCRIPTION
**Pull request by kushankr**
1. Added two options in the 'Poll Settings' panel to allow a user to
select if he/she wants to display the close date and/or poll countdown.
2. Depending upon the user's selections, a close date and/or a poll
countdown is displayed in the poll's detail page.

### CODE REVIEW

**Comment by kushankr** [comment]
@rupalkhilari 

Please review my PR. Thanks, Rupal.

A couple of notes:
1. I have optimized my js code for JQuery DateTimepicker in this PR too. I was not very happy with my earlier code because there were several repetitive function calls and I thought that my code could be made more concise. I have tested it and it is working just like before - except that, IMO, the code quality is better (Plus it fixed one minor bug too).

2. As we discussed, I am allowing the user to select options in 'Poll Settings panel' - A user is allowed to select if he/she wants to display the poll closing date and/or poll countdown. However, I have added one extra feature - the check boxes are enabled only when the user selects a Poll Closing date.

3. For the countdown, I had to use Inline JS as I needed to access a template variable.

4. I have taken a few liberties in the design. If you do not like how poll close date and countdown is displayed, I can change that. I just thought that the current design was looking good. But Please feel free to suggest any changes.

I have tested the code and it seems to work well. 

I look forward to receiving your feedback, Rupal. Thanks,

**Comment by rupalkhilari** [comment]
Hi Kushank, I am a bit busy today so I shall check it out and definitely get back to you by Tuesday.
Thanks!

**Comment by kushankr** [comment]
Thank you, Rupal, for letting me know!

**Comment by rupalkhilari** [comment]
Thanks a lot, Kushank ! The refactored code looks really neat and works like a charm. 
Your PR is almost good to go, I have made a few comments inline. Please let me know in case you have any concerns. 

Thanks!

**Comment by kushankr** [comment]
@rupalkhilari 

Thank you so much, Rupal, for your valuable feedback. 
I worked on your feedback and have committed the latest code. Please review it once.

Thanks, Rupal!

**Comment by kushankr** [comment]
Hi Rupal,

Sorry about that! I have now placed <hr> tag in 'create.html'. I thought that you were talking about 'detail.html'. I should have checked the inline comment.

Thanks.

**Pull request merged**
